// Code generated by generate.py. DO NOT EDIT.

package postgres

import (
	"fmt"
	"strings"
)

type ConstraintError struct {
	Constaint  string
  Type       string
	TableName  string
	ColumnName string
}

func (c ConstraintError) Error() string {
  if c.Type == "Unique" {
    return fmt.Sprintf(
      "unique constraint violation: '%s' has already taken. please try with someother %s",
      c.ColumnName,
      c.ColumnName,
    )
  }

  return ""
}

func IsConstraintError(err error) (bool,error) {
	if err == nil {
		return false,err
	}

	errStr := err.Error()
	for i := range ConstraintErrors {
		if strings.Contains(errStr, ConstraintErrors[i].Constaint) {
			return true,ConstraintErrors[i]
		}
	}

	return false,err
}
var ConstraintErrors = [1]ConstraintError{
	{
Constaint: "Department_name_unique",
Type: "Unique",
TableName: "department_master",
ColumnName: "department_name",
},
    }
